---
title: "Lab 06 - Conveying the right message through visualisation"
author: [XIAOYU JIANG,MAREN, XIAOJUN LUO]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(lubridate)
```


### Exercise 1

```{r create-data}
df <- tribble(
  ~date, ~mask, ~nomask,
  "7/12/2020", 25, 9,
  "7/13/2020", 20, 9,
  "7/14/2020", 20, 9,
  "7/15/2020", 20.5,10,
  "7/16/2020", 20,10,
  "7/17/2020", 20, 9.5,
  "7/18/2020", 20.5, 9.5,
  "7/19/2020", 20, 9,
  "7/20/2020", 20.5,8.5,
  "7/21/2020", 21.2, 8.5,
  "7/22/2020", 20,8.5,
  "7/23/2020", 20, 8.5,
  "7/24/2020", 20.5,10,
  "7/25/2020", 19,10,
  "7/26/2020", 19.5,10,
  "7/27/2020", 17, 9.5,
  "7/28/2020", 16.5, 9.5,
  "7/29/2020", 16.5,9.5,
  "7/30/2020", 16, 10,
  "7/31/2020", 15.5,9,
  "8/1/2020", 16,9,
  "8/2/2020", 16,9,
  "8/3/2020", 16,9,)
```


### Exercise 2

```{r better-viz}
df %>%
  mutate(
    mdy_format = mdy(date)
  ) %>%

  ggplot(mapping = aes(x = mdy_format)) +
  geom_line(mapping = aes(y = mask, colour = "blue")) +
  geom_line(mapping = aes(y = nomask, colour = "orange"))
```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
